# Generated by Django 6.0 on 2026-01-26 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_remove_project_category_project_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(help_text='Main/cover image for this project', upload_to='gallery/'),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for this image', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display (lower = first)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='gallery.project')),
            ],
            options={
                'verbose_name': 'Additional Image',
                'verbose_name_plural': 'Additional Images',
                'ordering': ['order', 'id'],
            },
        ),
    ]
