# Generated by Django 6.0 on 2026-02-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_project_image_projectimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order within the season section (lower = first)'),
        ),
        migrations.AddField(
            model_name='project',
            name='season',
            field=models.CharField(blank=True, choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall'), ('winter', 'Winter'), ('holiday', 'Holiday Decor')], help_text='Assign a season to group photos in the gallery', max_length=20),
        ),
    ]
