# Generated by Django 6.0 on 2026-02-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_project_options_project_order_project_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='season',
            field=models.CharField(blank=True, choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall'), ('winter', 'Winter')], help_text='Assign a season to group photos in the gallery', max_length=20),
        ),
    ]
