# Generated by Django 6.0 on 2026-02-09 09:54

from django.db import migrations


def add_holiday_decor_category(apps, schema_editor):
    """Add 'Holiday Decor' as a project category."""
    ProjectCategory = apps.get_model('gallery', 'ProjectCategory')
    # Get the next order value
    max_order = ProjectCategory.objects.order_by('-order').values_list('order', flat=True).first()
    next_order = (max_order or 0) + 1
    ProjectCategory.objects.get_or_create(
        slug='holiday-decor',
        defaults={'name': 'Holiday Decor', 'order': next_order},
    )


def remove_holiday_decor_category(apps, schema_editor):
    """Reverse: remove 'Holiday Decor' category."""
    ProjectCategory = apps.get_model('gallery', 'ProjectCategory')
    ProjectCategory.objects.filter(slug='holiday-decor').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_remove_holiday_from_season_choices'),
    ]

    operations = [
        migrations.RunPython(add_holiday_decor_category, remove_holiday_decor_category),
    ]
