# Generated by Django 6.0 on 2026-04-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='client_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='location',
            field=models.CharField(blank=True, help_text='e.g., Upper West Side', max_length=100),
        ),
    ]
