# Generated by Django 6.0 on 2025-12-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, help_text='Address or neighborhood', max_length=200)),
                ('property_type', models.CharField(blank=True, choices=[('rooftop', 'Rooftop/Terrace'), ('penthouse', 'Penthouse'), ('townhouse', 'Townhouse/Backyard'), ('commercial', 'Commercial'), ('other', 'Other')], max_length=20)),
                ('services_needed', models.JSONField(default=list, help_text='Selected services')),
                ('referral_source', models.CharField(blank=True, choices=[('google', 'Google Search'), ('referral', 'Friend/Family Referral'), ('returning', 'Returning Customer'), ('social', 'Social Media'), ('other', 'Other')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_contacted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
            ],
            options={
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
