# Generated by Django 6.0 on 2026-01-14 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinquiry',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contactinquiry',
            name='property_type',
        ),
    ]
