# Generated by Django 6.0 on 2025-12-30 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.TextField(help_text='Brief description for cards', max_length=200)),
                ('full_description', models.TextField(help_text='Detailed description for service page')),
                ('icon', models.CharField(blank=True, help_text="Bootstrap icon class, e.g., 'bi-droplet'", max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='services/heroes/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Service Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SubService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, help_text='Bootstrap icon class', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/sub/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_services', to='services.servicecategory')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
